### ISSUE TITLE
Add "Do Not Disturb" mode to the extension

### ISSUE THREAD

**Issue by idoshamun** [dailynowco/daily-apps#14]
Following dailynowco/daily#54, we would like to implement a "Do Not Disturb" (DND) mode, during this mode every time the user opens a new tab, the browser will be redirected to Google's default new tab. In order to open Daily when DND is turned on, the user must click on the extension button. When activated the user must state for how long DND should last.

The header features a new button for turning on DND with context menu to choose the duration.
![image](https://user-images.githubusercontent.com/1993245/61118784-25f54900-a4a2-11e9-98cc-8aeeb19247a2.png)

The new button is just like the buttons on its sides but it uses the `timer` icon, [it can be found here](https://github.com/dailynowco/daily-apps/blob/master/packages/extension/src/components/DaHeader.vue#L30). Once clicked, it should open a `DaContextMenu` (an example for context menu [can be found here](https://github.com/dailynowco/daily-apps/blob/master/packages/extension/src/routes/Home.vue#L82)).

Once enabled, all relevant data should be stored in the `ui` module of vuex, the cache plugin will take care to automatically store it on the storage.

To enforce DND, we need to create a new router guard [just like here](https://github.com/dailynowco/daily-apps/blob/master/packages/extension/src/standalone/standalone.js#L60), which checks the state and if it detects DND is on it should redirect to https://www.google.com/_/chrome/newtab.
Please note that if the user clicks on the button it should not redirect.

When DND is on, a message is shown below the header.
![image](https://user-images.githubusercontent.com/1993245/61118898-62c14000-a4a2-11e9-954c-3180a473497f.png)
This is message is fixed to the center of the header and when clicking on the `x` button it should cancel this mode.

**Comment by KieranHolroyd** [comment]
as the dnd bar at the top whilst active looks similar in design to a toast notification, i suggest either changing the design to seem more like a permanent fixture and have the close button more clear, like a timer with a line through it, or have a confirm message, like change the colour and text of the notification.

**Comment by idoshamun** [comment]
@KieranHolroyd thank you very much for the feedback. I can totally relate to what you are saying, let me take it offline and discuss with @tsahimatsliah. I will get back to you on this one :)

**Comment by idoshamun** [comment]
Following @KieranHolroyd, I would like to present the new design of the DND notification:
![image](https://user-images.githubusercontent.com/1993245/61636946-5a85b380-ac9f-11e9-95dd-082e6593e1fd.png)

And this is what happens if clicking on the DND icon while DND is on:
![image](https://user-images.githubusercontent.com/1993245/61637046-80ab5380-ac9f-11e9-96a3-351328a11ccc.png)

Let me know what you think

**Comment by KieranHolroyd** [comment]
looks good, it looks like how i'd imagined doing it, and i feel it takes any confusion away

**Comment by idoshamun** [comment]
Awesome!
@zd-zero please note the changes :)
