### ISSUE TITLE
Add client-side search for publications

### ISSUE THREAD

**Issue by idoshamun** [dailynowco/daily-apps#17]
The publication list in the side menu should have the same search bar you can find in the tag list. Same design and UX should be applied, the only difference is that this search should be client side.

**Comment by Andrei0872** [comment]
Is anybody working on this?

**Comment by idoshamun** [comment]
Hi @Andrei0872,
No one is working on this one. Would you like to give it a go?

**Comment by Andrei0872** [comment]
Hi @idoshamun, of course!

**Comment by idoshamun** [comment]
You are the best!
Feel free to reach out to me for whatever reason.
I'm available on [Daily's Slack](https://slack.dailynow.co/) :)
