### ISSUE TITLE
Tooltip component

### ISSUE THREAD

**Issue by idoshamun** [dailynowco/daily-apps#34]
We would like to add a tooltip component to our components library. This tooltip will be used for the extension and other future apps. One can apply relevant design to an already existing tooltip component like: https://github.com/Akryum/v-tooltip
The tooltip should support both bright and dark themes.

Access to our InVision project will be given to the contributor :)

![tooltip design](https://user-images.githubusercontent.com/1993245/63520741-e472a780-c4fd-11e9-8f10-05712ea8126a.png)

**Comment by wtfua92** [comment]
@idoshamun Hi there. Do you still need help with this feature? I would like to contribute :)

**Comment by idoshamun** [comment]
Hi @wtfua92! Would love your help. Ping me a message on our Slack, I would like to invite you to InVision. https://slack.dailynow.co/
