### ISSUE TITLE
Disable request source field while submitting a request

### ISSUE THREAD

**Issue by idoshamun** [dailynowco/daily-apps#36]
Currently when a user requests a source it might take a little while until the server confirms the request. In the meantime, many users click again and another request is sent. We should the disable the submit button while the request is sent. This is very easy to do by simply adding `disabled` attribute to the button which will automatically apply the relevant design as well.

![image](https://user-images.githubusercontent.com/1993245/63679374-d7a1cc80-c7f9-11e9-8365-8a5e82e04a8e.png)

**Comment by randalvance** [comment]
I am working on this one too #39

**Comment by idoshamun** [comment]
You are the best! Will code review everything tomorrow probably
