### ISSUE TITLE
Show creation time of post

### ISSUE THREAD

**Issue by idoshamun** [dailynowco/daily-apps#44]
Following https://github.com/dailynowco/daily/issues/39, we would like to show the creation time of a post so the user can easily understand which posts are new. The creation time will replace the tags and on hover the tags will be displayed instead of the creation time (in card mode only).

Access to our InVision project will be given to the contributor :)
![card mode design](https://user-images.githubusercontent.com/1993245/64564010-500ba000-d359-11e9-8890-88270943bc6d.png)

![insane mode](https://user-images.githubusercontent.com/1993245/64564043-631e7000-d359-11e9-8248-05516e7050d8.png)

**Comment by wtfua92** [comment]
I would like to work on the issue :)

**Comment by idoshamun** [comment]
Assigned you. Thank you very much 😊
