### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by shamay-dev** [dailynowco/daily-apps#65]
Hi, 
I am trying to build the extension and I am getting an error:
```yarn serve```
 ERROR  Failed to compile with 41 errors

dependencies were not found
`To install them, you can run: npm install --save @daily/components/icons @daily/components/icons/arrow @daily/components/icons/bookmark @daily/components/icons/card @daily/components/icons/github @daily/components/icons/google @daily/components/icons/hamburger @daily/components/icons/hashtag @daily/components/icons/line @daily/components/icons/link @daily/components/icons/logo @daily/components/icons/magnifying @daily/components/icons/mobile @daily/components/icons/moon @daily/components/icons/ph @daily/components/icons/plus @daily/components/icons/sun @daily/components/icons/terminal @daily/components/icons/timer @daily/components/icons/user @daily/components/icons/user_daily @daily/components/icons/v @daily/components/icons/x @daily/services`

But, when I try to run this line, I am getting the error:
`Could not install from "@daily/components/icons/arrow" as it does not contain a package.json file.`

Anything I missed?

**Comment by idoshamun** [comment]
Hi @shamay-dev,

I'm sorry for such a late reply, I somehow missed your issue.
You don't have to run this `npm install` command.
Make sure to run these commands before the first time:
```
npx lerna bootstrap
npx lerna run build
```
It will initialize correctly your repo.
