### ISSUE TITLE
New animation for card hover

### ISSUE THREAD

**Issue by idoshamun** [dailynowco/daily-apps#78]
According to https://github.com/dailynowco/daily/issues/119, the current animation for card hover causes bad user experience so we would like to change it.

We would like to suggest a new animation instead of the existing one:
- The card should move up `4px` using `translateY` and transition should be set to `0.4s ease-out`.
- The image inside the card should keep its current scaling but should be set to `0.4s ease-out` as well.
- The tricky part is that once the card is hovered a new element should be created that will serve as background layer for a cool box-shadow effect. The element can be created by using the psueo-element `:after`. The element should fill the card with `16px` margin for top and sides. The box-shadow should be `0 16px 24px 0 rgba(0,0,0,0.24)` for the light palette and `0 16px 24px 0 rgba(0,0,0,0.4)` for the default (dark) palette. Again transition on the box-shadow should be set to `0.4s ease-out`
![New element with box shadow](https://user-images.githubusercontent.com/1993245/70644457-b7ccd200-1c4b-11ea-88e4-ba06f475c99a.png)

**Comment by sshanzel** [comment]
Thank you very much for this, will be working on this one now <3

**Comment by idoshamun** [comment]
Thank you @sshanzel, I've assigned you to this issue. Please reach out for everything :)
