### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by idoshamun** [dailynowco/daily-apps#84]
We would like to implement a few keyboard shortcuts to allow users to interact with Daily without the mouse.

Bindings:
`h,j,k,l` - Navigate between blog posts (`h` - left. `j` - down, `k` - up, `l` - right). In insane mode `h,l` should do nothing.
`b` - Bookmark selected post.
`/` - Open and focus the search bar

When a post is focused it should like it is hovered.

For more information: https://github.com/dailynowco/daily/issues/122

**Comment by sshanzel** [comment]
Wow that was quick! Would love to start working on this ❤️

**Comment by idoshamun** [comment]
Thank you!
